### ISSUE TITLE
Bug？

### ISSUE THREAD

**Issue by EthaleW** [Derimius/Scarab#1]
Hi I'm new here so I'm not sure whether this is the right place to say that I caught a  bug in ur code...In line 10 and in line 54 'RT3' might be 'RT2' ? Thx for share code it really helps me a lot!!

**Comment by Derimius** [comment]
Yes, absolutely! I just saw it too. It arose from when I was relabelling my servos with the naming convention so as to make it easier to follow by the general public. 
I'm currently running the edits now. It wasn't just lines 10 and 54, though.
What I initially did was a 'Find and Replace' operation which accidentally converted all "Right Tibia 2" servos to "Right Tibia 3", but I'm sorting out the issues now. 
Thank you so much for your observation xoxo.

**Comment by Derimius** [comment]
This is the naming convention I came up with
![IMG_20231013_152211](https://github.com/Derimius/Scarab/assets/11166266/d890b732-0285-458e-a352-a1812ad631d8)

**Comment by Derimius** [comment]
It's been sorted out now. Thanks, once again, for the observation.
